rover:
  id: 1
  timeToMars: 3000
server:
  port: 8083
  servlet:
    context-path: /api
spring:
  output:
    ansi:
      enabled: always
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/RoverDB
    username: root
    password: 123
  jpa:
    openInView: true
    show-sql: false
    generateDdl: true
    database: postgresql
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  main:
      allow-circular-references: true